Repository hong-bin95/algo_pirates, pull requests merged in 2023-03, with the labels that each got.

#2 [LHE] 3월 8일
  .DS_Store
  LHE/.DS_Store
  LHE/202303/.DS_Store
  LHE/202303/08/.DS_Store
  LHE/202303/08/Main_1010_다리놓기.java
  LHE/202303/08/Main_10972_다음순열.java
  LHE/202303/08/Main_10973_이전순열.java
  LHE/202303/08/Main_2407_조합.java
Labels: 조합론, DP

#4 230308
  LHJ/202303/08/bj_1010_다리놓기.cpp
  LHJ/202303/08/bj_10972_다음순열.cpp
  LHJ/202303/08/bj_10973_이전순열.cpp
  LHJ/202303/08/bj_2407_조합.java
Labels: 조합론, DP

#6 [LHE] 3월 9일
  .DS_Store
  LHE/.DS_Store
  LHE/202303/.DS_Store
  LHE/202303/09/Main_10974_모든순열.java
  LHE/202303/09/Main_1244_스위치켜고끄기.java
  LHE/202303/09/Main_25176_청정수열.java
  LHE/202303/09/Main_25501_재귀의귀재.java
Labels: 구현, 시뮬레이션, 문자열, 재귀, 그리디, 수학, 브루트포스, 백트레킹

#7 [BYJ] 3월 8일 ~ 3월 9일
  .idea/.gitignore
  202303/08/Main_1010_배연주.py
  202303/08/Main_10972_배연주.py
  202303/08/Main_10973_배연주.py
  202303/08/Main_2407_배연주.py
  202303/09/Main_10974_배연주.py
  202303/09/Main_1244_배연주.py
  202303/09/Main_25176_배연주.py
  202303/09/Main_25501_배연주.py
Labels: 조합론, 구현, 문자열, 재귀, 그리디, 수학

#8 [LJH] 0308 -1
  202303/08/Main_1010_이정현.java
  202303/08/Main_2407_이정현.java
  202303/09/Main_10974_이정현.java
  202303/09/Main_25501_이정현.java
Labels: 조합론, DP

#9 [BYJ] 3월 10일
  202303/10/Main_10828.py
  202303/10/Main_17478.py
  202303/10/Main_18258.py
  202303/10/Main_7568.py
Labels: 구현, 재귀, 그리디, 브루트포스, 자료구조

#11 [LHE] 3월 10일
  .DS_Store
  LHE/.DS_Store
  LHE/202303/.DS_Store
  LHE/202303/10/Main_10828_스택.java
  LHE/202303/10/Main_17478_재귀함수가뭔가요.java
  LHE/202303/10/Main_18258_큐2.java
  LHE/202303/10/Main_7568_덩치.java
Labels: 구현, 재귀, 브루트포스, 자료구조

#20 [BYJ] 3월 11일 ~ 3월 12일
  202303/11/15235.py
  202303/11/2003.py
  202303/11/24444.py
  202303/11/24479.py
  202303/12/1260.py
  202303/12/21921.py
  202303/12/24445.py
  202303/12/24480.py
Labels: 구현, 시뮬레이션, 자료구조, BFS, DFS
